### ISSUE TITLE
PyPI doesn't link to this repo, and vice versa

### ISSUE THREAD

**Issue by DMRobertson** [erikjohnston/rust-jaeger-python-client#4]
It's hard to find this source code!

**Comment by MadLittleMods** [comment]
~~@DMRobertson What's the PyPI link for this package? https://pypi.org/project/rust-jaeger-python-client/ just 404's~~ -> https://pypi.org/project/rust-python-jaeger-reporter/ (`rust_python_jaeger_reporter`)

**Comment by DMRobertson** [comment]
Sorry, I should have written that down when I raised this :facepalm:
