### ISSUE TITLE
No source distributions published to PyPI

### ISSUE THREAD

**Issue by reivilibre** [erikjohnston/rust-jaeger-python-client#7]
https://pypi.org/project/rust-python-jaeger-reporter/#files

I'm not entirely sure on what the right workflow is for building the manylinux wheels AND an sdist and publishing those to PyPI, but alternatively as an addition to the current release procedure, an sdist could be built with

```
maturin sdist
```

(cite https://github.com/PyO3/maturin#source-distribution)

and then uploaded with twine as per usual.

This should then mean that any Python interpreter on any platform (perhaps needing a Rust compiler) can install straight from PyPI.

**Comment by clokep** [comment]
I wonder if we can use [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) to get macOS in there too?
